spring.application.name=PizzeriaExpress
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
server.servlet.context-path=/api
springdoc.api-docs.path=/docs

# Uncomment if needed for testing
spring.jpa.hibernate.ddl-auto=update